version: "3"

services:

    mysql:
        image: mysql:8.2.0
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=mysql
        volumes:
            - mysqldata:/var/lib/mysql
volumes:
        mysqldata:
          driver: local